### ISSUE TITLE
Unable to login 

### ISSUE THREAD

**Issue by ram-dev007** [JioTV-Go/jiotv_go#462]
### Bug description

![IMG-20241019-WA0031](https://github.com/user-attachments/assets/38c73a78-7279-4cc7-a63c-942f8c999cef)

### Steps to reproduce

Unable to login, not using jiofiber or jio network

### Relevant log output

```shell
Unable to login
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by itsyourap** [comment]
Which version of JioTV Go are you using?

**Comment by Learner00100** [comment]
Same error,
Mine version:3.11

![IMG_20241025_093110.jpg](https://github.com/user-attachments/assets/c4229046-a65a-444b-a63d-d73caba18ae6)

**Comment by ashish3805** [comment]
@itsyourap @Learner00100 I am facing the same issue, platform is Android 11 Sony TV. I am using Termux.

```bash
OTP sent to your mobile number
Enter OTP: 350104
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x930475c]

goroutine 1 [running]:
log.(*Logger).output(0x0, 0x0, 0x2, 0xb02f928)
	log/log.go:203 +0x3c
log.(*Logger).Println(...)
	log/log.go:276
github.com/jiotv-go/jiotv_go/v3/pkg/utils.GetDeviceID()
	github.com/jiotv-go/jiotv_go/v3/pkg/utils/utils.go:333 +0xb0
github.com/jiotv-go/jiotv_go/v3/pkg/utils.LoginVerifyOTP({0xb092030, 0xd}, {0xb2b9dd8, 0x6})
	github.com/jiotv-go/jiotv_go/v3/pkg/utils/utils.go:128 +0x8c
github.com/jiotv-go/jiotv_go/v3/cmd.LoginOTP()
	github.com/jiotv-go/jiotv_go/v3/cmd/login.go:69 +0x330
main.main.func5(0xb067500)
	github.com/jiotv-go/jiotv_go/v3/main.go:146 +0x14
github.com/urfave/cli/v2.(*Command).Run(0xb12c548, 0xb067500, {0xb02aae8, 0x1, 0x1})
	github.com/urfave/cli/v2@v2.27.4/command.go:276 +0x7b4
github.com/urfave/cli/v2.(*Command).Run(0xb12c488, 0xb067480, {0xb00ec30, 0x2, 0x2})
	github.com/urfave/cli/v2@v2.27.4/command.go:269 +0xaac
github.com/urfave/cli/v2.(*Command).Run(0xb12cb48, 0xb0673c0, {0xb018048, 0x3, 0x3})
	github.com/urfave/cli/v2@v2.27.4/command.go:269 +0xaac
github.com/urfave/cli/v2.(*App).RunContext(0xb0039e8, {0x988fbc8, 0x9c70ec8}, {0xb018048, 0x3, 0x3})
	github.com/urfave/cli/v2@v2.27.4/app.go:333 +0x62c
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.27.4/app.go:307
main.main()
	github.com/jiotv-go/jiotv_go/v3/main.go:239 +0x1b38
```

**Comment by rabilrbl** [comment]
Is it working now? It should be fixed from  Jio's end

**Comment by ashish3805** [comment]
I tried again today, it’s not working

**Comment by itsyourap** [comment]
![Umm](https://github.com/user-attachments/assets/f38695c1-2c69-4f4f-8210-11624e29bc6e)
This is unexpected! I am not able to recreate the issue.
